services:
  postgres:
    image: postgres:15
    container_name: postgres-api-starter
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TenantDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq-api-starter
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: api-starter
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DatabaseSettings__ConnectionString=Host=postgres;Database=TenantDb;Username=postgres;Password=root;Include Error Detail=true
      - HangfireSettings__Storage__ConnectionString=Host=postgres;Database=TenantDb;Username=postgres;Password=root;Include Error Detail=true
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  seq_data: